apiVersion: apps/v1
kind: Deployment
metadata:
  name: kmart-webapp
spec:
  selector:
    matchLabels:
      app: kmart-webapp
  template:
    metadata:
      labels:
        app: kmart-webapp
    spec:
      containers:
      - name: kmart-webapp
        image: vipinpr77/kmart:1.0
        env:
        - name: SECRET_KEY
          value: "django-insecure-5m_#ue4$qkq3c54r1#s=k2y=@$+m_&wdml4#d7=@@08)&rhfmz"
        - name: DEBUG
          value: "True"
        - name: DATABASE_ENGINE
          value: "django.db.backends.postgresql"
        - name: DATABASE_NAME
          value: "kinomart_new"
        - name: DATABASE_HOST
          value: "kmart-postgres-service"
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: email_host_username
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: email_host_password
        - name: DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: database_user
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: database_password
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000


---
apiVersion: v1
kind: Service
metadata:
  name: kmart-webapp-service
spec:
  selector:
    app: kmart-webapp
  ports:
  - port: 8000
    targetPort: 8000

