apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kmart-postgres-db
spec:
  selector:
    matchLabels:
      app: kmart-postgres-db
  serviceName: kmart-db-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kmart-postgres-db
    spec:
      containers:
      - name: kmart-postgres-db
        image: postgres
        ports:
        - containerPort: 5432
          name: postgres-port
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
    volumes:
    - name: data
      hostPath:
        path: <needs to be added>
