apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kmart-postgres-db
spec:
  selector:
    matchLabels:
      app: kmart-postgres-db
  serviceName: kmart-postgres-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kmart-postgres-db
    spec:
      containers:
      - name: kmart-postgres-db
        image: postgres
        env:
        - name: SECRET_KEY
          value: "django-insecure-5m_#ue4$qkq3c54r1#s=k2y=@$+m_&wdml4#d7=@@08)&rhfmz"
        - name: DEBUG
          value: "True"
        - name: DATABASE_ENGINE
          value: "django.db.backends.postgresql"
        - name: POSTGRES_DB
          value: "kinomart_new"
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: database_user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: env-secrets
              key: database_password

        ports:
        - containerPort: 5432
          name: postgres-port
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        hostPath:
          path: /data/kinomart-postgres


---
apiVersion: v1
kind: Service
metadata:
  name: kmart-postgres-service
spec:
  selector:
    app: kmart-postgres-db
  ports:
  - port: 5432
    targetPort: 5432

